/**
 * bike-stores-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Customer } from './customer';
import { OrderItem } from './order-item';
import { Staff } from './staff';
import { Store } from './store';


export interface Order { 
    orderId?: number;
    customerId?: number | null;
    orderStatus?: number;
    orderDate?: string;
    requiredDate?: string;
    shippedDate?: string | null;
    storeId?: number;
    staffId?: number;
    customer?: Customer;
    staff?: Staff;
    store?: Store;
    orderItems?: Array<OrderItem> | null;
}

