/**
 * bike-stores-api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Order } from './order';
import { Store } from './store';


export interface Staff { 
    staffId?: number;
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    phone?: string | null;
    active?: number;
    storeId?: number;
    managerId?: number | null;
    manager?: Staff;
    store?: Store;
    inverseManager?: Array<Staff> | null;
    orders?: Array<Order> | null;
}

